// <auto-generated />
using System;
using Eggodia.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eggodia.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506052518_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Eggodia.API.model.Carta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Era")
                        .HasColumnType("int");

                    b.Property<int>("EscudoMaximo")
                        .HasColumnType("int");

                    b.Property<string>("Habilidad")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PuntosAtaque")
                        .HasColumnType("int");

                    b.Property<string>("RutaEscena")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RutaImagen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("VidaMaxima")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("cartas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Era = 3,
                            EscudoMaximo = 250,
                            Habilidad = "Fuego eterno",
                            Nombre = "Dragón",
                            PuntosAtaque = 280,
                            RutaEscena = "res://cartas prime/Dragon_prime.tscn",
                            RutaImagen = "res://imagenes/CartasPng/DragonCart.png",
                            Tipo = "Místico",
                            VidaMaxima = 350
                        },
                        new
                        {
                            Id = 2,
                            Era = 3,
                            EscudoMaximo = 500,
                            Habilidad = "Rocas escudo: +200 ESC a 2 aliados",
                            Nombre = "Golem",
                            PuntosAtaque = 350,
                            RutaEscena = "res://cartas prime/Golem_prime.tscn",
                            RutaImagen = "res://imagenes/CartasPng/GolemCart.png",
                            Tipo = "Místico",
                            VidaMaxima = 450
                        },
                        new
                        {
                            Id = 3,
                            Era = 3,
                            EscudoMaximo = 220,
                            Habilidad = "Magia arcana",
                            Nombre = "Maguín",
                            PuntosAtaque = 250,
                            RutaEscena = "res://cartas prime/Maguin_prime.tscn",
                            RutaImagen = "res://imagenes/CartasPng/MaguinCart.png",
                            Tipo = "Místico",
                            VidaMaxima = 200
                        },
                        new
                        {
                            Id = 4,
                            Era = 2,
                            EscudoMaximo = 300,
                            Habilidad = "Guardia real",
                            Nombre = "Soldado Real",
                            PuntosAtaque = 150,
                            RutaEscena = "res://cartas prime/SoldadoReal_prime.tscn",
                            RutaImagen = "res://imagenes/CartasPng/SoldRealCart.png",
                            Tipo = "Medieval",
                            VidaMaxima = 250
                        },
                        new
                        {
                            Id = 5,
                            Era = 2,
                            EscudoMaximo = 450,
                            Habilidad = "Forma gigante: x2 ATK y ESC por 2 turnos",
                            Nombre = "Torre",
                            PuntosAtaque = 350,
                            RutaEscena = "res://cartas prime/Torre_prime.tscn",
                            RutaImagen = "res://imagenes/CartasPng/TorreCart.png",
                            Tipo = "Medieval",
                            VidaMaxima = 500
                        },
                        new
                        {
                            Id = 6,
                            Era = 2,
                            EscudoMaximo = 150,
                            Habilidad = "Sacrificio",
                            Nombre = "Peón",
                            PuntosAtaque = 100,
                            RutaEscena = "res://cartas prime/Peon_prime.tscn",
                            RutaImagen = "res://imagenes/CartasPng/PeonCart.png",
                            Tipo = "Medieval",
                            VidaMaxima = 150
                        },
                        new
                        {
                            Id = 7,
                            Era = 2,
                            EscudoMaximo = 550,
                            Habilidad = "La mejor sopa",
                            Nombre = "Encebollado",
                            PuntosAtaque = 450,
                            RutaEscena = "res://cartas prime/Encebollado_prime.tscn",
                            RutaImagen = "res://imagenes/CartasPng/EncebolladoCart.png",
                            Tipo = "Medieval",
                            VidaMaxima = 500
                        },
                        new
                        {
                            Id = 8,
                            Era = 2,
                            EscudoMaximo = 250,
                            Habilidad = "Salto en L: x2 daño a 2 carriles",
                            Nombre = "Caballo",
                            PuntosAtaque = 200,
                            RutaEscena = "res://cartas prime/Caballo_prime.tscn",
                            RutaImagen = "res://imagenes/CartasPng/CaballoCart.png",
                            Tipo = "Medieval",
                            VidaMaxima = 230
                        },
                        new
                        {
                            Id = 9,
                            Era = 2,
                            EscudoMaximo = 300,
                            Habilidad = "Dominio total",
                            Nombre = "Dama",
                            PuntosAtaque = 350,
                            RutaEscena = "res://cartas prime/Dama_prime.tscn",
                            RutaImagen = "res://imagenes/CartasPng/DamaCart.png",
                            Tipo = "Medieval",
                            VidaMaxima = 350
                        },
                        new
                        {
                            Id = 10,
                            Era = 1,
                            EscudoMaximo = 350,
                            Habilidad = "Furia primitiva",
                            Nombre = "T-Rex",
                            PuntosAtaque = 400,
                            RutaEscena = "res://cartas prime/TRex_prime.tscn",
                            RutaImagen = "res://imagenes/CartasPng/TReXCart.png",
                            Tipo = "Primordial",
                            VidaMaxima = 400
                        },
                        new
                        {
                            Id = 11,
                            Era = 1,
                            EscudoMaximo = 200,
                            Habilidad = "Ataque en profundidad",
                            Nombre = "Tiburón",
                            PuntosAtaque = 230,
                            RutaEscena = "res://cartas prime/Tiburon_prime.tscn",
                            RutaImagen = "res://imagenes/CartasPng/TiburonCart.png",
                            Tipo = "Primordial",
                            VidaMaxima = 300
                        },
                        new
                        {
                            Id = 12,
                            Era = 1,
                            EscudoMaximo = 380,
                            Habilidad = "Tinta bloqueadora: paraliza 2 tropas cercanas",
                            Nombre = "Calamar Gigante",
                            PuntosAtaque = 370,
                            RutaEscena = "res://cartas prime/CalamarG_prime.tscn",
                            RutaImagen = "res://imagenes/CartasPng/CalamarGCart.png",
                            Tipo = "Primordial",
                            VidaMaxima = 400
                        });
                });

            modelBuilder.Entity("Eggodia.API.model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DañoTotal")
                        .HasColumnType("int");

                    b.Property<int>("Derrotas")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Empates")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Victorias")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
